ctx_max_tokens: 120000
confidence_threshold: 0.8
checkpoint_threshold: 0.5  # Context usage for auto-checkpoint
agents:
  backend:
    worktree: ../wt-backend
    persona: backend.yaml
    capabilities: [api, database, python]
  frontend:
    worktree: ../wt-frontend
    persona: frontend.yaml
    capabilities: [web, ui, typescript, react]
  ios:
    worktree: ../wt-ios
    persona: ios.yaml
    capabilities: [swift, mobile]
  infra:
    worktree: ../wt-infra
    persona: infra.yaml
    capabilities: [docker, k8s, ci-cd]
orchestration:
  max_parallel: 4
  token_compression: true  # UltraCompressed for long prompts
