apiVersion: v1
kind: Namespace
metadata:
  name: leanvibe-agent-hive
  labels:
    # Pod Security Standards enforcement
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    # Additional security labels
    security.leanvibe.com/tier: production
    security.leanvibe.com/classification: internal
---
apiVersion: policy/v1
kind: PodSecurityPolicy
metadata:
  name: leanvibe-agent-hive-psp
  labels:
    app.kubernetes.io/name: leanvibe-agent-hive
    app.kubernetes.io/component: security
spec:
  # Privilege and access controls
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  allowedCapabilities: []
  
  # Host controls
  hostNetwork: false
  hostIPC: false
  hostPID: false
  hostPorts: []
  
  # User and group controls
  runAsUser:
    rule: 'MustRunAsNonRoot'
  runAsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1000
        max: 65535
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1000
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1000
        max: 65535
  
  # Filesystem controls
  readOnlyRootFilesystem: true
  allowedHostPaths: []
  
  # Volume controls
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
  
  # SELinux
  seLinux:
    rule: 'RunAsAny'
  
  # AppArmor
  allowedUnsafeSysctls: []
  forbiddenSysctls:
    - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: leanvibe-psp-user
  labels:
    app.kubernetes.io/name: leanvibe-agent-hive
    app.kubernetes.io/component: security
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames:
  - leanvibe-agent-hive-psp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: leanvibe-psp-binding
  labels:
    app.kubernetes.io/name: leanvibe-agent-hive
    app.kubernetes.io/component: security
roleRef:
  kind: ClusterRole
  name: leanvibe-psp-user
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: agent-hive-service-account
  namespace: leanvibe-agent-hive
- kind: ServiceAccount
  name: prometheus-service-account
  namespace: leanvibe-agent-hive