# LeanVibe Agent Hive Configuration
# Centralized configuration for the LeanVibe AI orchestration system
# Environment variables can override settings using LEANVIBE_ prefix
# Example: LEANVIBE_SYSTEM_LOG_LEVEL=DEBUG

# System-wide settings
system:
  log_level: INFO
  debug_mode: false
  max_concurrent_agents: 4
  context_max_tokens: 120000
  checkpoint_threshold: 0.85  # Context usage for auto-checkpoint
  confidence_threshold: 0.8
  health_check_interval: 30   # Health check interval in seconds
  max_concurrent_tasks: 10    # Maximum number of concurrent tasks

# Agent configurations
agents:
  claude:
    # Production CLI path
    cli_path: "claude-code"
    # Testing CLI path (mock)
    test_cli_path: ".claude/testing/mock_cli/mock_claude.py"
    timeout: 300  # 5 minutes
    max_retries: 3
    capabilities:
      - "code_generation"
      - "code_review"
      - "debugging"
      - "refactoring"
      - "testing"
    resource_limits:
      max_memory_mb: 512
      max_cpu_percent: 80
    
  gemini:
    # Production CLI path
    cli_path: "gemini"
    # Testing CLI path (mock)
    test_cli_path: ".claude/testing/mock_cli/mock_gemini.py"
    timeout: 180  # 3 minutes
    max_retries: 2
    capabilities:
      - "code_review"
      - "architecture_review"
      - "performance_review"
      - "security_review"
    resource_limits:
      max_memory_mb: 256
      max_cpu_percent: 60

# Task queue settings
task_queue:
  max_queue_size: 1000
  default_priority: 5
  cleanup_interval: 3600  # 1 hour
  max_task_age_hours: 24

# State management
state_management:
  # Fast checkpoints (JSON/SQLite)
  fast_checkpoints:
    enabled: true
    interval_seconds: 300  # 5 minutes
    max_checkpoints: 100
    storage_path: ".claude/state/checkpoints"
  
  # Git milestones (major checkpoints)
  git_milestones:
    enabled: true
    auto_tag: true
    tag_prefix: "milestone-"
    cleanup_old_tags: true
    max_tags: 50

# Monitoring and alerting
monitoring:
  metrics_enabled: true
  dashboard_enabled: true
  dashboard_port: 8080
  health_check_interval: 60  # seconds
  
  alerts:
    high_error_rate_threshold: 0.1  # 10%
    slow_response_threshold: 30  # seconds
    memory_usage_threshold: 0.9  # 90%

# Development/Testing settings
development:
  use_mock_cli: true   # Set to true for testing (default for development)
  debug_mode: true     # Enable debug mode in development
  verbose_logging: true
  test_data_path: "testing/test_data"     # Path to test data
  test_coverage_target: 80                # Target test coverage percentage
  
  # Mock CLI settings
  mock_settings:
    claude_delay: 1.0
    gemini_delay: 0.8
    failure_rate: 0.05  # 5% failure rate for testing
    mock_response_delay: 0.1  # Mock response delay in seconds

# Security settings
security:
  enable_input_validation: true
  sanitize_outputs: true
  rate_limiting:
    enabled: true
    max_requests_per_minute: 60
    burst_limit: 10

# Performance settings
performance:
  async_task_timeout: 600  # 10 minutes
  connection_pool_size: 10
  cache_enabled: true
  cache_ttl: 3600  # 1 hour
  
  # Circuit breaker settings
  circuit_breaker:
    failure_threshold: 5
    recovery_timeout: 60
    half_open_max_calls: 3

# Logging configuration
logging:
  format: "%(asctime)s %(levelname)s %(name)s %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"
  file_enabled: true                      # Enable file logging
  file_path: "logs/leanvibe.log"          # Log file path
  max_file_size: "10MB"                   # Maximum log file size
  backup_count: 5                         # Number of backup log files
  console_enabled: true                   # Enable console logging
  correlation_tracking: true             # Enable correlation ID tracking
  structured_logging: true               # Enable structured logging (JSON format)

# Environment-specific overrides
# Production environment should override development defaults
environments:
  production:
    system:
      debug_mode: false
    development:
      use_mock_cli: false
      debug_mode: false
      verbose_logging: false
    monitoring:
      alerts:
        enabled: true
        
  testing:
    system:
      debug_mode: true
    development:
      use_mock_cli: true
    logging:
      file_enabled: false
      console_enabled: true