# Prometheus configuration for LeanVibe Agent Hive
# Production monitoring setup with comprehensive metrics collection

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'leanvibe-agent-hive'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # Alertmanager will be added in future iterations
          # - alertmanager:9093

# Rules for alerting and recording
rule_files:
  - "alerts.yml"
  - "recording_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # LeanVibe Agent Hive main application
  - job_name: 'agent-hive'
    static_configs:
      - targets: ['agent-hive:8000']
    scrape_interval: 15s
    metrics_path: /metrics
    honor_labels: true
    scrape_timeout: 10s

  # LeanVibe Webhook Server
  - job_name: 'agent-hive-webhook'
    static_configs:
      - targets: ['agent-hive:8080']
    scrape_interval: 30s
    metrics_path: /metrics

  # LeanVibe API Gateway
  - job_name: 'agent-hive-gateway'
    static_configs:
      - targets: ['agent-hive:8081']
    scrape_interval: 30s
    metrics_path: /metrics

  # PostgreSQL metrics (via postgres_exporter if available)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s
    # Note: Requires postgres_exporter to be set up

  # Redis metrics (via redis_exporter if available)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    # Note: Requires redis_exporter to be set up

  # NGINX metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 30s
    metrics_path: /metrics

  # Node exporter for system metrics (if available)
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 30s

  # Docker container metrics (via cAdvisor if available)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['localhost:8080']
    scrape_interval: 30s

# Remote write configuration for long-term storage (optional)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint"
#     basic_auth:
#       username: "username"
#       password: "password"

# Storage configuration
storage:
  tsdb:
    retention.time: 15d
    retention.size: 10GB