apiVersion: v1
kind: Service
metadata:
  name: agent-hive-nodeport
  labels:
    app.kubernetes.io/name: leanvibe-agent-hive
    app.kubernetes.io/component: api
    environment: development
spec:
  type: NodePort
  ports:
  - name: http
    port: 8000
    targetPort: http
    nodePort: 30800
    protocol: TCP
  - name: webhook
    port: 8080
    targetPort: webhook
    nodePort: 30880
    protocol: TCP
  - name: gateway
    port: 8081
    targetPort: gateway
    nodePort: 30881
    protocol: TCP
  selector:
    app.kubernetes.io/name: leanvibe-agent-hive
    app.kubernetes.io/component: api