apiVersion: v1
kind: Secret
metadata:
  name: agent-hive-secrets
  namespace: leanvibe-agent-hive
  labels:
    app.kubernetes.io/name: leanvibe-agent-hive
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # Base64 encoded secrets (replace with actual values in production)
  # postgres-password: cGFzc3dvcmQ=  # "password"
  postgres-password: cHJvZHVjdGlvbl9wYXNzd29yZA==  # "production_password"
  redis-password: ""  # Empty for development, set in production
  jwt-secret: c3VwZXJfc2VjdXJlX2p3dF9rZXlfZm9yX3Byb2R1Y3Rpb24=  # "super_secure_jwt_key_for_production"
  api-key: YWdlbnRfaGl2ZV9hcGlfa2V5XzIwMjU=  # "agent_hive_api_key_2025"
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: leanvibe-agent-hive
  labels:
    app.kubernetes.io/name: leanvibe-agent-hive
    app.kubernetes.io/component: tls
type: kubernetes.io/tls
data:
  # TLS certificate and key (replace with real certificates)
  # Use cert-manager or manual certificate management
  tls.crt: LS0tLS1CRUdJTi0tLS0t  # Base64 encoded certificate
  tls.key: LS0tLS1CRUdJTi0tLS0t  # Base64 encoded private key